jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/workspace

    steps:
      - add_ssh_keys
      - checkout
      - setup_docker_engine

      -run:
        name: build
        command: docker build --rm=false -t vendigo/mongo-backup .

      - deploy:
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
            docker push vendigo/mongo-backup
