jobs:
  build:
    docker:
      - image: alpine:latest

    working_directory: ~/workspace

    steps:
      - add_ssh_keys
      - checkout
      - setup_docker_engine

      - deploy:
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
            docker build --rm=false -t vendigo/mongo-backup .
            docker push vendigo/mongo-backup
